version: '3.8'

services:
  emqx:
    image: emqx/emqx:5.8
    container_name: emqx
    restart: unless-stopped
    ports:
      - "1883:1883"     # MQTT 端口
      - "8083:8083"     # MQTT over WebSocket
      - "18083:18083"   # EMQX Dashboard
    networks:
      - emqx_net

  nginx:
    image: nginx:latest
    container_name: nginx_emqx
    ports:
      - "80:80"
      - "443:443"
      - "53:53/udp" # DNS 端口
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro  #ro :read only 
    depends_on:
      - emqx
    networks:
      - emqx_net

networks:
  emqx_net:
    driver: bridge
